export const weatherImages = {
  1003: require("../../assets/images/partlycloudy.png"),
  1186: require("../../assets/images/moderaterain.png"),
  1063: require("../../assets/images/moderaterain.png"),
  1000: require("../../assets/images/sun.png"),
  1009: require("../../assets/images/cloud.png"),
  1006: require("../../assets/images/cloud.png"),
  1180: require("../../assets/images/moderaterain.png"),
  1183: require("../../assets/images/moderaterain.png"),
  1189: require("../../assets/images/moderaterain.png"),
  1192: require("../../assets/images/heavyrain.png"),
  1195: require("../../assets/images/heavyrain.png"),
  1198: require("../../assets/images/heavyrain.png"),
  1201: require("../../assets/images/heavyrain.png"),
  1243: require("../../assets/images/heavyrain.png"),
  1273: require("../../assets/images/heavyrain.png"),
  1030: require("../../assets/images/mist.png"),
  1087: require("../../assets/images/heavyrain.png"),
  other: require("../../assets/images/moderaterain.png"),
  1066: require("../../assets/images/moderaterain.png"),
  1069: require("../../assets/images/moderaterain.png"),
  1072: require("../../assets/images/moderaterain.png"),
  1114: require("../../assets/images/moderaterain.png"),
};
